export enum Role {
    ADMIN = 'ADMIN',
    ACCOUNTANT = 'ACCOUNTANT',
    TEACHER = 'TEACHER',
    STUDENT = 'STUDENT',
    PARENT = 'PARENT',
    DEVELOPER = 'DEVELOPER',
    STORE_MANAGER = 'STORE_MANAGER',
    SUPERADMIN = 'SUPERADMIN'
}

export enum PaymentMode {
    CASH = 'CASH',
    CHEQUE = 'CHEQUE',
    BANK_TRANSFER = 'BANK_TRANSFER',
    UPI = 'UPI',
    CARD = 'CARD',
    NET_BANKING = 'NET_BANKING',
    RAZORPAY = 'RAZORPAY',
    STRIPE = 'STRIPE'
}

export enum PaymentStatus {
    PENDING = 'PENDING',
    VERIFIED = 'VERIFIED',
    FAILED = 'FAILED',
    REFUNDED = 'REFUNDED'
}

export enum NotificationChannel {
    SMS = 'SMS',
    EMAIL = 'EMAIL',
    WHATSAPP = 'WHATSAPP',
    IN_APP = 'IN_APP'
}

export enum NotificationStatus {
    PENDING = 'PENDING',
    SENT = 'SENT',
    FAILED = 'FAILED'
}

export enum AuditAction {
    PAYMENT_RECORDED = 'PAYMENT_RECORDED',
    PAYMENT_APPROVED = 'PAYMENT_APPROVED',
    PAYMENT_FAILED = 'PAYMENT_FAILED',
    RECEIPT_GENERATED = 'RECEIPT_GENERATED',
    FEE_STRUCTURE_CREATED = 'FEE_STRUCTURE_CREATED',
    FEE_STRUCTURE_MODIFIED = 'FEE_STRUCTURE_MODIFIED',
    FEE_STRUCTURE_DELETED = 'FEE_STRUCTURE_DELETED',
    STUDENT_CREATED = 'STUDENT_CREATED',
    STUDENT_UPDATED = 'STUDENT_UPDATED',
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
    BRANCH_CREATED = 'BRANCH_CREATED',
    FEE_ASSIGNED = 'FEE_ASSIGNED',
    STOCK_INWARD = 'STOCK_INWARD',
    STOCK_OUTWARD = 'STOCK_OUTWARD',
    ITEM_CREATED = 'ITEM_CREATED',
    ITEM_UPDATED = 'ITEM_UPDATED',
    ITEM_DELETED = 'ITEM_DELETED',
    SUPPLIER_ADDED = 'SUPPLIER_ADDED',
    INQUIRY_CREATED = 'INQUIRY_CREATED',
    INQUIRY_UPDATED = 'INQUIRY_UPDATED',
    INQUIRY_DELETED = 'INQUIRY_DELETED'
}
