'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Sidebar from '../../components/Sidebar';
import Link from 'next/link';
import { useAuth } from '../../context/AuthContext';
import api from '../../services/api';

const formatRupees = (paise: number) => `₹${(paise / 100).toLocaleString('en-IN')}`;

export default function ReceiptsPage() {
    const { user, loading } = useAuth();
    const router = useRouter();
    const [receipts, setReceipts] = useState<any[]>([]);
    const [fetching, setFetching] = useState(false);
    const [search, setSearch] = useState('');
    const BASE_URL = (process.env.NEXT_PUBLIC_API_URL || 'https://bss-ssiti-erp-and-fee-system.onrender.com/api').replace('/api', '');

    useEffect(() => { if (!loading && !user) router.push('/login'); }, [user, loading, router]);

    const fetchReceipts = async () => {
        setFetching(true);
        try {
            const { data } = await api.get('/receipts?limit=30');
            setReceipts(data.data || []);
        } catch { /* */ } finally { setFetching(false); }
    };

    useEffect(() => { if (user) fetchReceipts(); }, [user]);

    if (loading || !user) return null;

    const filtered = receipts.filter((r) => {
        const lc = search.toLowerCase();
        return !search || r.receiptNumber?.toLowerCase().includes(lc)
            || r.payment?.studentFee?.student?.name?.toLowerCase().includes(lc);
    });

    return (
        <div className="layout">
            <Sidebar />
            <div className="main-content">
                <header className="header">
                    <div>
                        <div className="header-title">🧾 Receipt History</div>
                        <div className="header-subtitle">{receipts.length} receipts generated</div>
                    </div>
                </header>

                <div className="page-content">
                    <div className="card mb-4">
                        <div className="card-body" style={{ padding: '12px 16px' }}>
                            <input type="text" className="form-control" placeholder="🔍 Search by receipt number or student name..."
                                value={search} onChange={(e) => setSearch(e.target.value)} />
                        </div>
                    </div>

                    <div className="card">
                        <div className="table-wrap" style={{ border: 'none' }}>
                            <table className="table">
                                <thead>
                                    <tr>
                                        <th>Receipt No.</th>
                                        <th>Student</th>
                                        <th>Class</th>
                                        <th>Amount Paid</th>
                                        <th>Payment Mode</th>
                                        <th>Date</th>
                                        <th>Generated By</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {fetching ? (
                                        <tr><td colSpan={8} className="text-center" style={{ padding: 40 }}><div className="spinner" style={{ margin: '0 auto' }} /></td></tr>
                                    ) : filtered.length === 0 ? (
                                        <tr><td colSpan={8} className="text-center text-muted" style={{ padding: 40 }}>No receipts found</td></tr>
                                    ) : filtered.map((r) => (
                                        <tr key={r.id}>
                                            <td>
                                                <span className="badge badge-primary" style={{ fontFamily: 'monospace', fontSize: 11 }}>
                                                    {r.receiptNumber}
                                                </span>
                                            </td>
                                            <td>
                                                <b>{r.payment?.studentFee?.student?.name}</b>
                                                <br />
                                                <span className="text-sm text-muted">{r.payment?.studentFee?.student?.studentId}</span>
                                            </td>
                                            <td>{r.payment?.studentFee?.student?.class}</td>
                                            <td><b className="text-success">{formatRupees(r.payment?.amount || 0)}</b></td>
                                            <td><span className="badge badge-info">{r.payment?.mode}</span></td>
                                            <td>{new Date(r.createdAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</td>
                                            <td>{r.generatedBy?.name}</td>
                                            <td>
                                                <a
                                                    href={`${BASE_URL}${r.pdfUrl}`}
                                                    target="_blank"
                                                    rel="noopener noreferrer"
                                                    className="btn btn-accent btn-sm"
                                                >
                                                    📄 PDF
                                                </a>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>                <footer className="footer">
                    <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                        <span>&copy; 2026 Shri Sai I.T.I All rights reserved.</span>
                        <Link href="/terms" style={{ color: 'var(--primary-light)', textDecoration: 'none', fontWeight: 500, fontSize: '13px' }}>
                            Terms and Conditions
                        </Link>
                    </div>
                    <div>Developed by Rushikesh Pattiwar</div>
                </footer>
            </div>
        </div>
    );
}
