'use client';

import { useEffect, useState, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Sidebar from '../../components/Sidebar';
import Link from 'next/link';
import { useAuth } from '../../context/AuthContext';
import api from '../../services/api';

const formatRupees = (paise: number) => `₹${(paise / 100).toLocaleString('en-IN')}`;

function ReceiptsContent({ simulateParam }: { simulateParam: string | null }) {
    const { user, loading } = useAuth();
    const router = useRouter();
    const effectiveRole = (user?.role === 'DEVELOPER' && simulateParam) ? simulateParam.toUpperCase() : user?.role;

    const [receipts, setReceipts] = useState<any[]>([]);
    const [fetching, setFetching] = useState(false);
    const [search, setSearch] = useState('');

    useEffect(() => { if (!loading && !user) router.push('/login'); }, [user, loading, router]);

    const fetchReceipts = async () => {
        setFetching(true);
        try {
            const { data } = await api.get('/receipts?limit=30');
            setReceipts(data.data || []);
        } catch { /* */ } finally { setFetching(false); }
    };

    useEffect(() => { if (user) fetchReceipts(); }, [user]);

    if (loading || !user) return null;

    const filtered = receipts.filter((r) => {
        const lc = search.toLowerCase();
        return !search || r.receiptNumber?.toLowerCase().includes(lc)
            || r.payment?.studentFee?.student?.name?.toLowerCase().includes(lc);
    });

    const getBaseUrl = () => {
        return typeof window !== 'undefined' && window.location.hostname !== 'localhost' && window.location.hostname !== '127.0.0.1'
            ? 'https://bss-ssiti-erp-and-fee-system.onrender.com'
            : 'http://localhost:4000';
    };

    const canRefund = effectiveRole === 'ADMIN' || effectiveRole === 'DEVELOPER' || effectiveRole === 'SUPERADMIN' || effectiveRole === 'BRANCH_ADMIN';

    return (
        <div className="layout">
            <Sidebar />
            <div className="main-content">
                <header className="header">
                    <div>
                        <div className="header-title">🧾 Fee Receipts</div>
                        <div className="header-subtitle">Issued payment receipts & download PDFs</div>
                    </div>
                </header>

                <div className="page-content">
                    <div className="card mb-4">
                        <div className="card-body" style={{ padding: '12px 16px' }}>
                            <input
                                type="text" className="form-control" placeholder="🔍 Search receipt number or student name..."
                                value={search} onChange={(e) => setSearch(e.target.value)}
                            />
                        </div>
                    </div>

                    <div className="card">
                        <div className="card-body" style={{ padding: 0, overflowX: 'auto' }}>
                            <table className="table">
                                <thead>
                                    <tr>
                                        <th>Receipt No.</th>
                                        <th>Student</th>
                                        <th>Amount</th>
                                        <th>Mode</th>
                                        <th>Issued Date</th>
                                        <th>Generated By</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {fetching ? (
                                        <tr><td colSpan={7} className="text-center text-muted" style={{ padding: 40 }}><span className="spinner" /> Loading receipts...</td></tr>
                                    ) : filtered.length === 0 ? (
                                        <tr><td colSpan={7} className="text-center text-muted" style={{ padding: 40 }}>No receipts found</td></tr>
                                    ) : filtered.map((r) => (
                                        <tr key={r.id}>
                                            <td><span className="badge badge-primary">{r.receiptNumber}</span></td>
                                            <td>
                                                <b>{r.payment?.studentFee?.student?.name}</b>
                                                <div className="text-sm text-muted">{r.payment?.studentFee?.student?.studentId}</div>
                                            </td>
                                            <td><b style={{ color: 'var(--accent)' }}>{formatRupees(r.payment?.amount || 0)}</b></td>
                                            <td><span className="badge badge-neutral">{r.payment?.mode}</span></td>
                                            <td>{new Date(r.createdAt).toLocaleDateString('en-IN')}</td>
                                            <td>{r.generatedBy?.name}</td>
                                            <td>
                                                <div style={{ display: 'flex', gap: 6 }}>
                                                    <a
                                                        href={`${getBaseUrl()}${r.pdfUrl.startsWith('/api') ? r.pdfUrl : `/api${r.pdfUrl}`}`}
                                                        target="_blank"
                                                        rel="noopener noreferrer"
                                                        className="btn btn-accent btn-sm"
                                                    >
                                                        📄 PDF
                                                    </a>
                                                    {canRefund && r.payment?.status !== 'REFUNDED' && (
                                                        <button
                                                            className="btn btn-danger btn-sm"
                                                            style={{ padding: '4px 8px', fontSize: 11 }}
                                                            onClick={async () => {
                                                                const reason = prompt('Reason for fee refund:');
                                                                if (!reason) return;
                                                                try {
                                                                    await api.post(`/payments/${r.paymentId}/refund`, { reason });
                                                                    alert('✅ Fee refunded successfully!');
                                                                    fetchReceipts();
                                                                } catch (err: any) {
                                                                    alert(`❌ ${err.response?.data?.message || 'Refund failed'}`);
                                                                }
                                                            }}
                                                        >
                                                            ↩ Refund
                                                        </button>
                                                    )}
                                                </div>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

function SearchParamsLoader() {
    const searchParams = useSearchParams();
    const simulateParam = searchParams.get('simulate');
    return <ReceiptsContent simulateParam={simulateParam} />;
}

export default function ReceiptsPage() {
    return (
        <Suspense fallback={<div className="layout"><Sidebar /><div className="main-content"><div className="page-content text-center text-muted" style={{ padding: 40 }}><span className="spinner" /> Loading receipts...</div></div></div>}>
            <SearchParamsLoader />
        </Suspense>
    );
}
